### ISSUE TITLE
windows下安装报编码问题

### ISSUE THREAD

**Issue by Nwj-9** [425776024/nlpcda#2]
**ubuntu下安装不报错**
具体报错：
Traceback (most recent call last):  \lib\site-packages\pip\_internal\cli\base_command.py", line 188, in _main                                                                                                status = self.run(options, args) 
 File "lib\site-packages\pip\_internal\cli\req_command.py", line 185, in wrapper return func(self, options, args)                                                                      File "lib\site-packages\pip\_internal\commands\install.py", line 398, in run installed = install_given_reqs(lib\site-packages\pip\_internal\req\__init__.py", line 67, in install_given_reqs requirement.install(
File "lib\site-packages\pip\_internal\req\req_install.py", line 804, in install install_wheel(                                                                                        File "lib\site-packages\pip\_internal\operations\install\wheel.py", line 622, in install_wheel                                                                                install_unpacked_wheel(                                                                               
File "lib\site-packages\pip\_internal\operations\install\wheel.py", line 596, in install_unpacked_wheel                                                                       rows = get_csv_rows_for_installed(                                                                    
File "lib\site-packages\pip\_internal\operations\install\wheel.py", line 247, in get_csv_rows_for_installed                                                                   for row in old_csv_rows:  UnicodeDecodeError: 'gbk' codec can't decode byte 0x8d in position 321: illegal multibyte sequence

**Comment by 425776024** [comment]
windows下似乎可能有这种编码错误
你的这样install之后，后续能正常导入使用吗？
因为是在Linux、Mac环境下开发，所以Ubuntu保证没问题的，但是，
只在部分windows下测试过，会有3种情况，正常安装，安装报错不能导入，安装报错能导入

**Comment by Nwj-9** [comment]
> windows下似乎可能有这种编码错误
> 你的这样install之后，后续能正常导入使用吗？
> 因为是在Linux、Mac环境下开发，所以Ubuntu保证没问题的，但是，
> 只在部分windows下测试过，会有3种情况，正常安装，安装报错不能导入，安装报错能导入

抱歉这么晚回复，虽然不知道为什么，不过的确可以正常使用了
